#!/bin/bash

java org.antlr.v4.Tool JavaLexer.g4
java org.antlr.v4.Tool  -no-listener -visitor JavaParser.g4

javac *.java






# all: SlothParser.class SlothVisitor.class Main.class
# @echo "All done"
# @echo to test the grammar w/o a Main:
# @echo 	grun Sloth program -tokens
# @echo 	grun Sloth program -tree
# @echo 	grun Sloth program -ps tree.ps
# 
# Main.class: Main.java
# javac Main.java
# 
# SlothVisitor.class: SlothVisitor.java
# javac SlothVisitor.java
# 
# SlothParser.class: SlothLexer.class SlothParser.java
# javac SlothParser.java
# 
# SlothParser.java: SlothParser.g4
# java org.antlr.v4.Tool -no-listener -visitor SlothParser.g4
# 
# SlothLexer.class: SlothLexer.java
# javac SlothLexer.java
# 
# SlothLexer.java: SlothLexer.g4
# 
# clean:
# rm -f *.class *.interp *.tokens SlothLexer.java SlothParser.java SlothParserBaseVisitor.java SlothParserVisitor.java
# 
